### ISSUE TITLE
Does it support gaps in the data ?

### ISSUE THREAD

**Issue by quazzie** [FormidableLabs/victory-line#46]
Like so: {
 { x: 0, y: 10 },
 { x: 1, y: 20 },
 { x: 2, y: null },
 { x: 3, y: null },
 { x: 4, y: 15 },
 { x: 5, y: 12 },
 ...
}

or how should you handle this ?
Thanks.

**Comment by boygirl** [comment]
@quazzie thanks for bringing this to my attention. I'll make a fix this week that splits line data into segments when there is null data, and creates a line for each segment.

**Comment by quazzie** [comment]
Great!

ons 2 dec 2015 20:46 Lauren <notifications@github.com> skrev:
