### ISSUE TITLE
d3-shape

### ISSUE THREAD

**Issue by bsr203** [FormidableLabs/victory-line#51]
Hello,

Do we need to use the whole d3 package, or the new module developed as part of D3 v4, which specifically for 

`
Who’s it for?
It’s for authoring new visualization tools, especially in conjunction with frameworks that already have a DOM abstraction and don’t need D3 selections (e.g., React, Angular, Ember). There are quite a few other new modules you might want, such as d3-color, d3-format, d3-time and d3-scale.
`

 as stated by Mike.

https://medium.com/@mbostock/introducing-d3-shape-73f8367e6d12#.qmvcco7m8

**Comment by boygirl** [comment]
@bsr203 Thanks! We looked into using d3-modules a few months ago, and were blocked by some polyfill issues with the modules. We decided to wait a bit for the modules to mature but we will definitely revisit.
