### ISSUE TITLE
Linkage to the interactive docs?

### ISSUE THREAD

**Issue by janusch** [FormidableLabs/victory-line#68]
Hello,
Just a minor thing...
I keep wondering why there is no link to the documentation on the victory components?
Wouldn't it be appropriate to link to `http://victory.formidable.com/docs/victory-line/` in the readme?

Kind Regards

**Comment by knowbody** [comment]
that would be great! mind sending the PR?

**Comment by janusch** [comment]
Sorry, a whole month passed. I was planning on adding this. Still hope to get around to it, if you havn't doen it by then.

**Comment by boygirl** [comment]
@janusch Thanks, but it should no longer be necessary. This repo is being deprecated, and code for VictoryLine will now be included in VictoryChart. I'll open an issue there to make sure the docs get linked though.

**Comment by janusch** [comment]
@boygirl Thank you for the heads-up. I will need to make some changes to my package.json. I am including the components on their own right now.
