### ISSUE TITLE
Error: invalid format: ,.NaNf

### ISSUE THREAD

**Issue by gnestor** [FormidableLabs/victory-line#76]
The following returns `Error: invalid format: ,.NaNf` for me:

```javascript
<VictoryChart>
        <VictoryLine y={(x) => Math.sin(2 * Math.PI * x)} />
</VictoryChart>
```
See it reproduced in this Tonic notebook (since Tonic is a Node.js environment, you have to use `ReactDOM.renderToString`): https://tonicdev.com/gnestor/victory-line-chart-nan

**Comment by F21** [comment]
Seeing the same issue here.

Maybe related: If I insert a `VictoryChart` with no customization (`<VictoryChart/>`), there isn't any default line graph either.

**Comment by gnestor** [comment]
You need to use `<VictoryLine />` to plot a line.

**Comment by F21** [comment]
A `VictoryChart` should plot a line by default. See the first example here: http://victory.formidable.com/docs/victory-chart

**Comment by dandelany** [comment]
Hi @gnestor and @F21 - sorry, we need to update the docs here as the API has changed a bit. Previously, when using the `y` accessor function, the argument was the `x` value. Now it is the entire data object, allowing you to access anything on that object to generate the y value. So if you replace this:

```
<VictoryLine y={(x) => Math.sin(2 * Math.PI * x)} />
```

with this:

```
<VictoryLine y={(d) => Math.sin(2 * Math.PI * d.x)} />
```

it should work. I will make sure the docs get updated tonight or tomorrow. Thanks for the heads up!

**Comment by dandelany** [comment]
[Here is JSfiddle btw](https://jsfiddle.net/oqwmvw2v/) - feel free to fork for further examples.

**Comment by gnestor** [comment]
That fixes it. Thanks @dandelany!
